name: "Merge Branches"
description: "Update the course repository when the learner completes a step."
author: "devvspaces"
branding:
  icon: "git-merge"
  color: "blue"
inputs:
  token:
    description: "Set to [secrets.GITHUB_TOKEN]."
    required: true
  from_branch:
    description: "Branch we want to merge to another branch"
    required: true
  to_branch:
    description: "Branch we want to merge another branch on"
    required: true
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        echo "Make sure we are on the $TO_BRANCH branch"
        git checkout $TO_BRANCH
        git pull

        echo "Merge $FROM_BRANCH and push to $TO_BRANCH"
        git config user.name github-actions
        git config user.email github-actions@github.com
        git merge --no-ff $FROM_BRANCH -m "[Automated] Merge $FROM_BRANCH to $TO_BRANCH"
        git push
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        FROM_BRANCH: ${{ inputs.from_branch }}
        TO_BRANCH: ${{ inputs.to_branch }}
